// Extension seed (spec 003 tech §5.3, spec 006 `tld_policies.description`). Used to build the TLD pool and the
// `tld_fit@1` options until the daily price data (milestone M4) tells us which extensions are actually sold.

/** Short description per extension; the text Jev reads in `tld_fit@1`. */
export const TLD_INFO: Record<string, string> = {
  com: 'the most recognised extension, for any website',
  net: 'general extension, often for networks and tech',
  org: 'for organisations, non-profits and communities',
  co: 'short, popular with startups and companies',
  io: 'popular with tech startups and developer tools',
  app: 'for apps and software (requires HTTPS)',
  xyz: 'cheap general extension, popular with new projects',
  online: 'general extension for online businesses',
  site: 'general extension for any website',
  dev: 'for developers and software projects (requires HTTPS)',
  ai: 'for artificial intelligence products',
  tech: 'for technology companies',
  so: 'short extension used by software products',
  sh: 'short extension liked by developers',
  cloud: 'for cloud services and hosting',
  software: 'for software products',
  tools: 'for tools and utilities',
  codes: 'for coding and developer projects',
  page: 'for simple pages (requires HTTPS)',
  wiki: 'for wikis and knowledge bases',
  digital: 'for digital products and services',
  shop: 'for online stores',
  store: 'for shops and stores',
  market: 'for marketplaces and markets',
  boutique: 'for small fashion and lifestyle shops',
  exchange: 'for exchanges and trading',
  cafe: 'for cafés and coffee places',
  kitchen: 'for kitchens, food and recipes',
  menu: 'for restaurants and menus',
  recipes: 'for recipe sites',
  restaurant: 'for restaurants',
  pizza: 'for pizza places',
  coffee: 'for coffee shops and roasters',
  blog: 'for blogs and personal writing',
  news: 'for news sites',
  press: 'for press and publishing',
  media: 'for media companies',
  tv: 'for video and TV channels',
  fm: 'for radio and podcasts',
  studio: 'for creative studios',
  show: 'for shows and entertainment',
  academy: 'for schools and training academies',
  courses: 'for online courses',
  school: 'for schools',
  education: 'for education',
  training: 'for training providers',
  college: 'for colleges',
  community: 'for communities and groups',
  club: 'for clubs and memberships',
  social: 'for social networks and communities',
  design: 'for designers and design studios',
  me: 'personal extension for individuals',
  art: 'for artists and galleries',
  gallery: 'for galleries and portfolios',
  work: 'for work, portfolios and jobs',
  name: 'for personal names',
  bio: 'for personal profiles and biographies',
  ngo: 'for non-governmental organisations',
  foundation: 'for foundations',
  charity: 'for charities',
  fund: 'for funds and fundraising',
  events: 'for events',
  live: 'for live events and streaming',
  careers: 'for job boards and careers pages',
  jobs: 'for job listings',
  homes: 'for homes and real estate',
  house: 'for houses and real estate',
  properties: 'for property listings',
  estate: 'for real estate',
  tours: 'for tours and travel experiences',
  holiday: 'for holidays and travel',
  voyage: 'for travel',
  travel: 'for travel businesses',
  hotel: 'for hotels',
  health: 'for health services',
  care: 'for care services',
  clinic: 'for clinics',
  doctor: 'for doctors',
  dental: 'for dentists',
  finance: 'for financial services',
  money: 'for money and finance',
  capital: 'for investment and capital',
  legal: 'for legal services',
  attorney: 'for attorneys',
  lawyer: 'for lawyers',
  family: 'for families',
  fun: 'for fun and entertainment',
  toys: 'for toy shops',
  gg: 'popular with gamers',
  games: 'for games',
  game: 'for a game',
  agency: 'for agencies',
  solutions: 'for business solutions',
  services: 'for service businesses',
  company: 'for companies',
  consulting: 'for consultancies',
  directory: 'for directories',
  guide: 'for guides',
  reviews: 'for review sites',
  info: 'for information sites',
  global: 'for international businesses',
  world: 'for global projects',
  luxury: 'for luxury brands',
  vip: 'for exclusive brands',
  eco: 'for eco-friendly brands',
  earth: 'for environmental projects',
  green: 'for green and sustainable brands',
  fit: 'for fitness',
  fitness: 'for fitness businesses',
  run: 'for running and sport',
  yoga: 'for yoga',
  coach: 'for coaches',
  fashion: 'for fashion',
  style: 'for style and fashion',
  beauty: 'for beauty brands',
  pet: 'for pets',
  pets: 'for pet businesses',
  dog: 'for dog lovers',
  vet: 'for veterinarians',
  photography: 'for photographers',
  photo: 'for photos',
  video: 'for video',
  film: 'for film',
  movie: 'for movies',
  music: 'for music',
  band: 'for bands',
  wedding: 'for weddings',
  love: 'for love and relationships',
  dating: 'for dating',
  garden: 'for gardens',
  farm: 'for farms',
  energy: 'for energy companies',
  solar: 'for solar businesses',
  industries: 'for industrial companies',
  trade: 'for trade',
  cars: 'for car businesses',
  auto: 'for automotive businesses',
  bike: 'for bikes',
  delivery: 'for delivery services',
  repair: 'for repair services',
  cleaning: 'for cleaning services',
  church: 'for churches',
  vote: 'for political campaigns',
  space: 'for creative spaces and coworking',
  insure: 'for insurance',
  tax: 'for tax services',
  loans: 'for lenders',
  credit: 'for credit services',
  accountant: 'for accountants',
  architect: 'for architects',
  construction: 'for construction',
  build: 'for builders',
  realty: 'for real estate agents',
  rentals: 'for rentals',
  security: 'for security companies',
  host: 'for hosting',
  marketing: 'for marketing',
  tips: 'for tips and how-tos',
  wine: 'for wine',
  beer: 'for beer',
  bar: 'for bars',
  jewelry: 'for jewellery',
  shoes: 'for shoes',
  furniture: 'for furniture',
  books: 'for books',
  gifts: 'for gifts',
  sport: 'for sport',
  // country and regional extensions
  in: 'India',
  'co.in': 'India (companies)',
  us: 'United States',
  uk: 'United Kingdom',
  'co.uk': 'United Kingdom',
  ca: 'Canada',
  au: 'Australia',
  'com.au': 'Australia',
  nz: 'New Zealand',
  'co.nz': 'New Zealand',
  ie: 'Ireland',
  de: 'Germany',
  fr: 'France',
  es: 'Spain',
  it: 'Italy',
  nl: 'Netherlands',
  be: 'Belgium',
  ch: 'Switzerland',
  at: 'Austria',
  se: 'Sweden',
  no: 'Norway',
  dk: 'Denmark',
  fi: 'Finland',
  pl: 'Poland',
  pt: 'Portugal',
  gr: 'Greece',
  cz: 'Czechia',
  ro: 'Romania',
  hu: 'Hungary',
  'com.tr': 'Turkey',
  ua: 'Ukraine',
  'com.br': 'Brazil',
  mx: 'Mexico',
  'com.mx': 'Mexico',
  'com.ar': 'Argentina',
  'com.co': 'Colombia',
  cl: 'Chile',
  pe: 'Peru',
  'co.za': 'South Africa',
  ng: 'Nigeria',
  'com.ng': 'Nigeria',
  ke: 'Kenya',
  'co.ke': 'Kenya',
  'com.eg': 'Egypt',
  ma: 'Morocco',
  ae: 'United Arab Emirates',
  sa: 'Saudi Arabia',
  'co.il': 'Israel',
  pk: 'Pakistan',
  'com.bd': 'Bangladesh',
  lk: 'Sri Lanka',
  'com.np': 'Nepal',
  sg: 'Singapore',
  'com.sg': 'Singapore',
  my: 'Malaysia',
  'com.my': 'Malaysia',
  id: 'Indonesia',
  'co.id': 'Indonesia',
  ph: 'Philippines',
  'com.ph': 'Philippines',
  'co.th': 'Thailand',
  vn: 'Vietnam',
  jp: 'Japan',
  'co.jp': 'Japan',
  kr: 'South Korea',
  'co.kr': 'South Korea',
  cn: 'China',
  hk: 'Hong Kong',
  tw: 'Taiwan',
  eu: 'European Union',
  asia: 'Asia',
  africa: 'Africa',
  lat: 'Latin America',
  // adult-only extensions (kept only for adult sites, spec 003 §5.3)
  xxx: 'adult content',
  adult: 'adult content',
  sex: 'adult content',
  porn: 'adult content',
};

export const BASE_TLDS = ['com', 'net', 'co', 'org', 'io', 'app', 'xyz', 'online', 'site'] as const;
export const ADULT_TLDS = new Set(['xxx', 'adult', 'sex', 'porn']);

/** geo_scope@1 key → local extensions, most common first. */
export const GEO_TLDS: Record<string, string[]> = {
  country_in: ['in', 'co.in'],
  country_us: ['us'],
  country_gb: ['uk', 'co.uk'],
  country_ca: ['ca'],
  country_au: ['com.au', 'au'],
  country_nz: ['co.nz', 'nz'],
  country_ie: ['ie'],
  country_de: ['de'],
  country_fr: ['fr'],
  country_es: ['es'],
  country_it: ['it'],
  country_nl: ['nl'],
  country_be: ['be'],
  country_ch: ['ch'],
  country_at: ['at'],
  country_se: ['se'],
  country_no: ['no'],
  country_dk: ['dk'],
  country_fi: ['fi'],
  country_pl: ['pl'],
  country_pt: ['pt'],
  country_gr: ['gr'],
  country_cz: ['cz'],
  country_ro: ['ro'],
  country_hu: ['hu'],
  country_tr: ['com.tr'],
  country_ua: ['ua'],
  country_br: ['com.br'],
  country_mx: ['mx', 'com.mx'],
  country_ar: ['com.ar'],
  country_co: ['com.co'],
  country_cl: ['cl'],
  country_pe: ['pe'],
  country_za: ['co.za'],
  country_ng: ['ng', 'com.ng'],
  country_ke: ['co.ke', 'ke'],
  country_eg: ['com.eg'],
  country_ma: ['ma'],
  country_ae: ['ae'],
  country_sa: ['sa'],
  country_il: ['co.il'],
  country_pk: ['pk'],
  country_bd: ['com.bd'],
  country_lk: ['lk'],
  country_np: ['com.np'],
  country_sg: ['sg', 'com.sg'],
  country_my: ['my', 'com.my'],
  country_id: ['id', 'co.id'],
  country_ph: ['ph', 'com.ph'],
  country_th: ['co.th'],
  country_vn: ['vn'],
  country_jp: ['jp', 'co.jp'],
  country_kr: ['kr', 'co.kr'],
  country_cn: ['cn'],
  country_hk: ['hk'],
  country_tw: ['tw'],
  region_europe: ['eu'],
  region_asia: ['asia'],
  region_latam: ['lat'],
  region_africa: ['africa'],
  region_middle_east: [],
  global: [],
  other_country: [],
};

/** Feature flag → fitting extensions (spec 003 tech §5.3 `FLAG_TLDS`). */
export const FLAG_TLDS: Record<string, string[]> = {
  feat_sells_physical: ['shop', 'store', 'market', 'boutique'],
  feat_sells_digital: ['shop', 'store', 'digital'],
  feat_software: ['io', 'app', 'so', 'tech', 'cloud', 'software'],
  feat_mobile_app: ['app'],
  feat_developer: ['dev', 'io', 'sh', 'tools', 'codes'],
  feat_ai: ['ai', 'io', 'tech'],
  feat_food: ['cafe', 'kitchen', 'menu', 'recipes', 'restaurant', 'pizza', 'coffee'],
  feat_articles: ['blog', 'news', 'press', 'media'],
  feat_media: ['tv', 'fm', 'media', 'studio', 'show'],
  feat_courses: ['academy', 'courses', 'school', 'education', 'training'],
  feat_community: ['community', 'club', 'social', 'org'],
  feat_marketplace: ['market', 'shop', 'store', 'exchange'],
  feat_portfolio: ['design', 'studio', 'me', 'art', 'gallery', 'work'],
  feat_personal: ['me', 'name', 'page', 'bio'],
  feat_nonprofit: ['org', 'ngo', 'foundation', 'charity', 'fund'],
  feat_donations: ['org', 'ngo', 'foundation', 'charity', 'fund'],
  feat_events: ['events', 'live'],
  feat_jobs: ['careers', 'work'],
  feat_real_estate: ['homes', 'house', 'properties', 'estate'],
  feat_travel: ['tours', 'holiday', 'voyage', 'travel'],
  feat_health: ['health', 'care', 'clinic', 'doctor'],
  feat_finance: ['finance', 'money', 'capital', 'fund'],
  feat_legal: ['legal', 'attorney', 'lawyer'],
  feat_school: ['school', 'academy', 'education', 'college'],
  feat_kids: ['family', 'fun', 'toys'],
  feat_gaming: ['gg', 'games', 'game', 'fun'],
  feat_crypto: ['xyz', 'finance'],
  feat_b2b: ['agency', 'solutions', 'services', 'company', 'consulting', 'digital'],
  feat_agency: ['agency', 'solutions', 'services', 'company', 'consulting', 'digital'],
  feat_directory: ['directory', 'guide', 'reviews', 'info'],
  feat_docs: ['dev', 'page', 'wiki', 'sh'],
  feat_multilingual: ['global', 'world'],
  feat_luxury: ['luxury', 'boutique', 'vip'],
  feat_eco: ['eco', 'earth', 'green'],
  feat_fitness: ['fit', 'fitness', 'run', 'yoga', 'coach'],
  feat_fashion_beauty: ['fashion', 'style', 'boutique', 'beauty'],
  feat_pets: ['pet', 'pets', 'dog', 'vet'],
};

/** Feature flag → seed words for generation (spec 003 tech §5.4 `FLAG_WORDS`). */
export const FLAG_WORDS: Record<string, string[]> = {
  feat_sells_physical: ['shop', 'store', 'goods'],
  feat_sells_digital: ['kit', 'pack', 'files'],
  feat_subscription: ['club', 'box', 'monthly'],
  feat_software: ['app', 'cloud', 'stack'],
  feat_developer: ['code', 'dev', 'stack'],
  feat_ai: ['mind', 'smart', 'neural'],
  feat_bookings: ['book', 'slot', 'reserve'],
  feat_local: ['local', 'corner', 'nearby'],
  feat_food: ['kitchen', 'table', 'fresh'],
  feat_articles: ['journal', 'notes', 'daily'],
  feat_media: ['studio', 'cast', 'channel'],
  feat_courses: ['learn', 'academy', 'class'],
  feat_community: ['circle', 'crew', 'together'],
  feat_marketplace: ['market', 'bazaar', 'exchange'],
  feat_portfolio: ['studio', 'works', 'folio'],
  feat_nonprofit: ['hope', 'care', 'together'],
  feat_donations: ['give', 'hope', 'fund'],
  feat_events: ['live', 'meet', 'fest'],
  feat_jobs: ['hire', 'talent', 'careers'],
  feat_real_estate: ['home', 'nest', 'key'],
  feat_travel: ['trip', 'journey', 'roam'],
  feat_health: ['care', 'well', 'heal'],
  feat_finance: ['capital', 'wealth', 'ledger'],
  feat_legal: ['law', 'counsel', 'legal'],
  feat_kids: ['little', 'tiny', 'play'],
  feat_gaming: ['play', 'quest', 'level'],
  feat_eco: ['green', 'earth', 'leaf'],
  feat_fitness: ['fit', 'move', 'strong'],
  feat_fashion_beauty: ['style', 'glow', 'chic'],
  feat_pets: ['paw', 'pet', 'tail'],
  feat_luxury: ['luxe', 'prime', 'gold'],
};
