// Keyword seeds for the rule-based fallback (spec 003 tech §5.5) and the safety fallback (spec 014 tech §5.3).
// All words are lemmas (lower case), matched against the lemmatized description.

/** site_type@1 keys → indicative lemmas. */
export const SITE_TYPE_KEYWORDS: Record<string, string[]> = {
  online_store: [
    'shop',
    'store',
    'sell',
    'buy',
    'order',
    'product',
    'ecommerce',
    'checkout',
    'ship',
    'boutique',
  ],
  saas_web_app: [
    'saas',
    'software',
    'platform',
    'dashboard',
    'tool',
    'automate',
    'automation',
    'api',
    'workflow',
    'subscription',
  ],
  mobile_app: ['app', 'android', 'ios', 'mobile', 'download', 'smartphone'],
  blog: ['blog', 'post', 'write', 'thought', 'journal', 'diary'],
  news_media: ['news', 'magazine', 'headline', 'journalism', 'report', 'media'],
  portfolio: ['portfolio', 'showcase', 'gallery', 'work', 'project', 'designer', 'photographer', 'artist'],
  personal_site: ['personal', 'cv', 'resume', 'myself', 'homepage', 'about'],
  agency_services: ['agency', 'consulting', 'consultancy', 'freelance', 'client', 'service', 'studio'],
  local_business: ['local', 'neighborhood', 'neighbourhood', 'nearby', 'town', 'city', 'area', 'visit'],
  restaurant_cafe: ['restaurant', 'cafe', 'bakery', 'coffee', 'menu', 'food', 'dine', 'pizza', 'kitchen'],
  nonprofit: [
    'nonprofit',
    'charity',
    'ngo',
    'donate',
    'donation',
    'volunteer',
    'cause',
    'rescue',
    'foundation',
  ],
  education_courses: [
    'course',
    'lesson',
    'tutor',
    'tutoring',
    'class',
    'learn',
    'teach',
    'student',
    'training',
  ],
  community_forum: ['community', 'forum', 'member', 'membership', 'discussion', 'club', 'group'],
  marketplace: ['marketplace', 'buyer', 'seller', 'vendor', 'listing', 'connect'],
  directory_listings: ['directory', 'listing', 'review', 'compare', 'find', 'guide'],
  event: ['event', 'conference', 'festival', 'summit', 'meetup', 'ticket'],
  startup_landing: ['startup', 'launch', 'waitlist', 'beta', 'product'],
  docs_open_source: ['documentation', 'docs', 'open', 'source', 'library', 'github', 'framework', 'sdk'],
  podcast_video: ['podcast', 'episode', 'youtube', 'channel', 'video', 'vlog', 'creator'],
  booking_service: ['book', 'booking', 'appointment', 'reservation', 'reserve', 'schedule', 'slot'],
  real_estate: ['property', 'rent', 'apartment', 'flat', 'house', 'realtor', 'estate'],
  healthcare_practice: [
    'clinic',
    'doctor',
    'therapist',
    'therapy',
    'dentist',
    'patient',
    'wellness',
    'physiotherapy',
  ],
  professional_practice: ['law', 'lawyer', 'legal', 'accountant', 'accounting', 'firm', 'attorney', 'tax'],
  job_board: ['job', 'hire', 'hiring', 'recruit', 'recruitment', 'career', 'vacancy'],
  game: ['game', 'gaming', 'gamer', 'play', 'player', 'esports'],
  other: [],
};

/** Feature flag → indicative lemmas (spec 003 §5.5: p = 0.7 when matched, else 0.1). */
export const FLAG_KEYWORDS: Record<string, string[]> = {
  feat_sells_physical: [
    'shop',
    'store',
    'sell',
    'ship',
    'deliver',
    'delivery',
    'product',
    'order',
    'buy',
    'handmade',
  ],
  feat_sells_digital: ['download', 'template', 'ebook', 'digital', 'preset', 'printable', 'course'],
  feat_subscription: ['subscription', 'subscribe', 'monthly', 'membership', 'plan', 'recurring'],
  feat_software: ['software', 'saas', 'platform', 'tool', 'app', 'dashboard', 'api'],
  feat_mobile_app: ['android', 'ios', 'mobile', 'smartphone'],
  feat_developer: ['developer', 'code', 'api', 'sdk', 'database', 'devops', 'programmer', 'cli', 'github'],
  feat_ai: ['ai', 'artificial', 'intelligence', 'machine', 'llm', 'chatbot', 'neural'],
  feat_bookings: ['book', 'booking', 'appointment', 'reservation', 'reserve', 'schedule', 'slot'],
  feat_local: ['local', 'neighborhood', 'neighbourhood', 'nearby', 'town', 'city', 'visit', 'store'],
  feat_food: [
    'food',
    'bakery',
    'bread',
    'cake',
    'restaurant',
    'cafe',
    'coffee',
    'recipe',
    'meal',
    'cook',
    'drink',
  ],
  feat_articles: ['blog', 'article', 'news', 'post', 'write', 'review', 'weekly'],
  feat_media: ['video', 'podcast', 'youtube', 'episode', 'channel', 'stream'],
  feat_courses: ['course', 'lesson', 'tutor', 'class', 'teach', 'learn', 'training', 'workshop'],
  feat_community: ['community', 'forum', 'member', 'discussion', 'club', 'meetup'],
  feat_marketplace: ['marketplace', 'seller', 'vendor', 'buyer', 'listing'],
  feat_portfolio: ['portfolio', 'gallery', 'showcase', 'work', 'photographer', 'designer', 'artist'],
  feat_personal: ['my', 'personal', 'cv', 'resume', 'freelance', 'myself', 'photographer'],
  feat_nonprofit: ['nonprofit', 'charity', 'ngo', 'cause', 'foundation', 'rescue', 'volunteer'],
  feat_donations: ['donate', 'donation', 'fundraise', 'fundraising', 'sponsor'],
  feat_events: ['event', 'ticket', 'concert', 'festival', 'conference', 'wedding'],
  feat_jobs: ['job', 'hire', 'hiring', 'recruit', 'career', 'vacancy'],
  feat_real_estate: ['property', 'rent', 'apartment', 'flat', 'house', 'realtor'],
  feat_travel: ['travel', 'tour', 'trip', 'hotel', 'holiday', 'homestay', 'tourist'],
  feat_health: ['health', 'clinic', 'doctor', 'therapy', 'wellness', 'medical', 'patient', 'fitness'],
  feat_finance: ['finance', 'bank', 'payment', 'invest', 'loan', 'insurance', 'money', 'crypto', 'tax'],
  feat_legal: ['legal', 'law', 'lawyer', 'attorney', 'contract'],
  feat_school: ['school', 'college', 'university', 'campus', 'student'],
  feat_kids: ['kid', 'child', 'children', 'family', 'toddler', 'baby', 'parent', 'toy'],
  feat_gaming: ['game', 'gaming', 'gamer', 'esports', 'console'],
  feat_crypto: ['crypto', 'bitcoin', 'blockchain', 'web3', 'nft', 'token', 'defi'],
  feat_b2b: ['business', 'b2b', 'enterprise', 'company', 'team', 'client', 'saas'],
  feat_agency: ['agency', 'consulting', 'consultant', 'freelance', 'client', 'studio'],
  feat_directory: ['directory', 'listing', 'review', 'compare', 'guide'],
  feat_docs: ['documentation', 'docs', 'open', 'source', 'library', 'github'],
  feat_multilingual: ['worldwide', 'international', 'global', 'multilingual', 'language', 'country'],
  feat_luxury: ['luxury', 'premium', 'exclusive', 'elegant', 'designer', 'gold', 'silver'],
  feat_eco: ['eco', 'sustainable', 'sustainability', 'green', 'organic', 'environment', 'climate', 'recycle'],
  feat_fitness: ['fitness', 'workout', 'gym', 'sport', 'yoga', 'run', 'fit', 'exercise', 'outdoor'],
  feat_fashion_beauty: [
    'fashion',
    'clothing',
    'clothes',
    'beauty',
    'makeup',
    'skincare',
    'jewelry',
    'jewellery',
    'style',
  ],
  feat_pets: ['pet', 'dog', 'cat', 'animal', 'puppy', 'vet'],
};

/** Words for the sensitive "gambling" category (spec 003 §5.6). */
export const GAMBLING_WORDS = [
  'casino',
  'bet',
  'betting',
  'gamble',
  'gambling',
  'poker',
  'lottery',
  'bookmaker',
  'slot',
];

/** Region words → geo_scope keys. */
export const REGION_WORDS: Record<string, string> = {
  europe: 'region_europe',
  european: 'region_europe',
  eu: 'region_europe',
  asia: 'region_asia',
  asian: 'region_asia',
  latam: 'region_latam',
  'latin america': 'region_latam',
  africa: 'region_africa',
  african: 'region_africa',
  'middle east': 'region_middle_east',
  worldwide: 'global',
  global: 'global',
  international: 'global',
};

/**
 * Country names, unambiguous adjectives and major cities → ISO code (only countries in `geo_scope@1`).
 * Adjectives that are also language names ("Spanish lessons") or common nouns ("turkey") are left out.
 * The fallback only needs to recognise a place when one is named (NFR-FEAT-004 is measured on Jev).
 */
export const GAZETTEER: Record<string, string[]> = {
  in: [
    'india',
    'indian',
    'mumbai',
    'delhi',
    'bangalore',
    'bengaluru',
    'pune',
    'chennai',
    'hyderabad',
    'kolkata',
    'ahmedabad',
    'jaipur',
    'lucknow',
    'kochi',
    'goa',
    'chandigarh',
    'indore',
    'surat',
    'nagpur',
    'bhopal',
  ],
  us: [
    'usa',
    'america',
    'american',
    'united states',
    'new york',
    'los angeles',
    'chicago',
    'houston',
    'san francisco',
    'seattle',
    'boston',
    'austin',
    'miami',
    'denver',
    'atlanta',
    'texas',
    'california',
    'florida',
  ],
  gb: [
    'uk',
    'britain',
    'british',
    'england',
    'scotland',
    'wales',
    'united kingdom',
    'london',
    'manchester',
    'birmingham',
    'edinburgh',
    'glasgow',
    'liverpool',
    'bristol',
    'leeds',
  ],
  ca: ['canada', 'canadian', 'toronto', 'vancouver', 'montreal', 'calgary', 'ottawa'],
  au: ['australia', 'australian', 'sydney', 'melbourne', 'brisbane', 'perth', 'adelaide'],
  nz: ['new zealand', 'auckland', 'wellington', 'christchurch'],
  ie: ['ireland', 'irish', 'dublin', 'cork'],
  de: ['germany', 'berlin', 'munich', 'hamburg', 'frankfurt', 'cologne'],
  fr: ['france', 'paris', 'lyon', 'marseille', 'toulouse', 'nice'],
  es: ['spain', 'madrid', 'barcelona', 'valencia', 'seville'],
  it: ['italy', 'rome', 'milan', 'naples', 'florence', 'turin'],
  nl: ['netherlands', 'amsterdam', 'rotterdam', 'utrecht'],
  be: ['belgium', 'belgian', 'brussels', 'antwerp'],
  ch: ['switzerland', 'swiss', 'zurich', 'geneva', 'basel'],
  at: ['austria', 'austrian', 'vienna', 'salzburg'],
  se: ['sweden', 'stockholm', 'gothenburg'],
  no: ['norway', 'oslo', 'bergen'],
  dk: ['denmark', 'copenhagen'],
  fi: ['finland', 'helsinki'],
  pl: ['poland', 'warsaw', 'krakow'],
  pt: ['portugal', 'lisbon', 'porto'],
  gr: ['greece', 'athens', 'thessaloniki'],
  cz: ['czechia', 'prague', 'brno'],
  ro: ['romania', 'bucharest'],
  hu: ['hungary', 'budapest'],
  tr: ['türkiye', 'istanbul', 'ankara', 'izmir'],
  ua: ['ukraine', 'kyiv', 'kiev', 'lviv'],
  br: ['brazil', 'brazilian', 'sao paulo', 'rio de janeiro', 'brasilia'],
  mx: ['mexico', 'mexican', 'mexico city', 'guadalajara', 'monterrey'],
  ar: ['argentina', 'argentinian', 'buenos aires'],
  co: ['colombia', 'colombian', 'bogota', 'medellin'],
  cl: ['chile', 'chilean', 'santiago'],
  pe: ['peru', 'peruvian', 'lima'],
  za: ['south africa', 'south african', 'johannesburg', 'cape town', 'durban'],
  ng: ['nigeria', 'nigerian', 'lagos', 'abuja'],
  ke: ['kenya', 'kenyan', 'nairobi', 'mombasa'],
  eg: ['egypt', 'egyptian', 'cairo', 'alexandria'],
  ma: ['morocco', 'moroccan', 'casablanca', 'marrakech'],
  ae: ['uae', 'emirates', 'emirati', 'dubai', 'abu dhabi', 'sharjah'],
  sa: ['saudi', 'saudi arabia', 'riyadh', 'jeddah'],
  il: ['israel', 'israeli', 'tel aviv', 'jerusalem'],
  pk: ['pakistan', 'pakistani', 'karachi', 'lahore', 'islamabad'],
  bd: ['bangladesh', 'bangladeshi', 'dhaka', 'chittagong'],
  lk: ['sri lanka', 'sri lankan', 'colombo'],
  np: ['nepal', 'kathmandu'],
  sg: ['singapore', 'singaporean'],
  my: ['malaysia', 'malaysian', 'kuala lumpur', 'penang'],
  id: ['indonesia', 'jakarta', 'bali', 'surabaya'],
  ph: ['philippines', 'manila', 'cebu'],
  th: ['thailand', 'bangkok', 'phuket', 'chiang mai'],
  vn: ['vietnam', 'hanoi', 'ho chi minh', 'saigon'],
  jp: ['japan', 'tokyo', 'osaka', 'kyoto', 'yokohama'],
  kr: ['korea', 'seoul', 'busan'],
  cn: ['china', 'beijing', 'shanghai', 'shenzhen', 'guangzhou'],
  hk: ['hong kong'],
  tw: ['taiwan', 'taiwanese', 'taipei'],
};

/** Phrases that suggest phishing, fraud or impersonation when Jev is unavailable (spec 014 tech §5.3). */
export const SAFETY_PATTERNS = {
  refuse: [
    // Intent, not topic: "a blog that teaches people to spot phishing" must stay allowed.
    /\b(steal\w*|harvest\w*|collect\w*|captur\w*|grab\w*)\s+(\w+\s+){0,3}(password|credential|login|card number|otp|pin)s?\b/i,
    /\b(phishing|scam)\s+(page|site|kit|website|operation|business|ring|campaign)\b(?!.{0,40}\b(awareness|spot|avoid|detect|protect|report))/i,
    // Harm to children, trafficking, stolen goods, identity theft, forged papers, hate platforms, gambling for minors.
    // Protective wording ("report child abuse material", "drug trafficking lawyer") stays allowed.
    /(?<!\b(protect\w*|prevent\w*|against|stop\w*|fight\w*|combat\w*|report\w*|detect\w*|remov\w*)\b.{0,30})\b(child|children|minors?|underage|kids?)\b.{0,30}\b(porn\w*|nudes?|(exploitation|abuse|explicit|sexual)\s+(material|content|images|videos|photos))\b/i,
    /\b(porn\w*|nudes?|explicit|sexual)\s+(\w+\s+){0,2}(of|with|featuring|involving)\s+(\w+\s+)?(child|children|minors?|underage|kids?)\b/i,
    /(?<!\b(anti|against|prevent\w*|stop\w*|fight\w*|combat\w*|ending|end)\W{1,3})\b(weapons?|arms|firearms?|guns?|drugs?)\s+(trafficking|smuggling)\b(?!\s+(prevention|awareness|survivors?|victims?|research|laws?|lawyers?|attorneys?|defen[cs]e|news|statistics|data|history|documentar\w*))/i,
    /\b(illegal|illicit)\s+(drugs?|narcotics|weapons?|firearms?)\s+(marketplace|market|shop|store|platform|site)\b/i,
    /\bstolen\s+(goods|items|cars?|phones?|property|bikes?|data)\s+(marketplace|market|shop|store|platform|site)\b/i,
    /\bidentity\s+theft\s+(service|kit|tools?|shop|platform)\b/i,
    /\b(counterfeit|fake|forged)\s+(documents?|passports?|id cards?|ids|driving licen[cs]es?|diplomas?|degrees?|certificates?)\s+(service|shop|store|seller|vendor|maker|platform)s?\b/i,
    /\bhate\s+(speech|group)\s+(platform|site|forum|website|community|network)\b/i,
    /\b(gambling|betting|casino|porn\w*|adult)\s+(sites?|apps?|games?|platforms?|websites?|services?|content|club)\s+for\s+(minors|kids|children|teens|teenagers|underage)\b/i,
    /\bsell\w*\s+(alcohol|vapes?|cigarettes|tobacco)\s+to\s+(minors|kids|children|teens|teenagers|underage)\b/i,
    /\b(fake|clone[ds]?|copy|replica|lookalike|look[- ]alike)\b.{0,40}\b(login|log-in|sign[- ]in|bank|paypal|wallet)\b/i,
    /\blooks?\s+(just\s+)?like\s+(my\s+|the\s+)?\w+'?s?\s+(bank|login|website)\b/i,
    // Selling or doing it, not talking about it ("a museum about counterfeit money" is fine).
    /\b(sell\w*|buy\w*|print\w*|make|making|ship\w*|offer\w*)\s+(\w+\s+){0,3}counterfeit\b/i,
    /\bcounterfeit\b.{0,40}\b(as genuine|as real|for sale)\b/i,
    /\b(sell\w*|buy\w*|download\w*|rent\w*|distribut\w*)\s+(\w+\s+){0,3}(ransomware|malware|botnet|exploit kits?)\b/i,
    /\blaunder\w*\s+(money|funds|cash)\b|\bmoney laundering services?\b/i,
    /\b(sell\w*|buy\w*)\s+(\w+\s+){0,2}stolen\s+(\w+\s+){0,2}(cards?|card numbers|accounts|identities)\b/i,
    /\b(sell\w*|buy\w*)\s+(illegal\s+)?(drugs|cocaine|heroin|meth|guns|weapons|firearms)\b/i,
  ],
  strictBrand: [
    /\b(just\s+like|clone\s+of|copy\s+of|same\s+as|imitat\w+|impersonat\w+)\b/i,
    /\b[Ll]ike\s+[A-Z][a-z]+\s+but\b/,
  ],
} as const;
