// Industry taxonomy v1 (spec 003 tech §5.1): 141 entries, at most 200 allowed. Each entry:
// [label (chip text + Jev option description), keywords (lemmas for the rule fallback), wordHints (seed words for
// generation, spec 004), tldHints (extra extensions for the TLD pool, spec 003 §5.3)].
// Changing labels changes the `industry@1` options, so it needs a new catalog version.

export const GROUP_LABELS: Record<string, string> = {
  food: 'Food & drink',
  retail: 'Shopping',
  tech: 'Technology',
  finance: 'Finance',
  health: 'Health & wellness',
  education: 'Education',
  services: 'Services',
  real_estate: 'Real estate',
  travel: 'Travel',
  media: 'Media',
  community: 'Community',
  nonprofit: 'Non-profit',
  lifestyle: 'Lifestyle',
  automotive: 'Automotive',
  entertainment: 'Entertainment',
  agriculture: 'Agriculture',
  industry: 'Industry',
  government_public: 'Public sector',
  personal: 'Personal',
  other: 'Other',
};

type Entry = [item: string, keywords: string, wordHints: string, tldHints: string];

const T: Record<string, Entry> = {
  food__bakery: [
    'Bakery',
    'bakery bread cake pastry sourdough croissant bake baker cupcake',
    'bake loaf crumb crust oven dough',
    'cafe kitchen',
  ],
  food__restaurant: [
    'Restaurant',
    'restaurant dine dining menu chef cuisine bistro eatery dinner',
    'table dine feast plate fork',
    'restaurant menu kitchen',
  ],
  food__cafe_coffee: [
    'Café & coffee',
    'cafe coffee espresso latte barista roastery tea',
    'brew bean cup roast mug',
    'cafe coffee',
  ],
  food__catering: [
    'Catering',
    'catering caterer buffet banquet party food corporate lunch',
    'feast serve platter spread',
    'kitchen events',
  ],
  food__food_delivery: [
    'Food delivery',
    'delivery deliver takeaway takeout meal order doorstep tiffin',
    'dash bite fresh go',
    'delivery menu',
  ],
  food__grocery: [
    'Grocery',
    'grocery groceries supermarket produce vegetable fruit pantry',
    'fresh basket cart market',
    'market shop',
  ],
  food__recipes_cooking: [
    'Recipes & cooking',
    'recipe cook cooking kitchen meal dish homemade',
    'cook stir spice simmer',
    'recipes kitchen',
  ],
  food__beverages: [
    'Beverages',
    'beverage drink juice brewery beer wine spirit soda kombucha',
    'sip pour brew tap',
    'wine beer bar',
  ],
  food__organic_health_food: [
    'Organic & health food',
    'organic vegan healthy superfood gluten keto plant natural',
    'green pure leaf root',
    'organic eco',
  ],
  food__sweets_confectionery: [
    'Sweets & confectionery',
    'sweet chocolate candy confectionery dessert ice cream mithai',
    'sugar treat cocoa honey',
    'shop',
  ],
  retail__fashion_clothing: [
    'Fashion & clothing',
    'fashion clothing clothes apparel dress shirt wear outfit',
    'wear thread style stitch',
    'fashion clothing shop',
  ],
  retail__jewelry: [
    'Jewelry',
    'jewelry jewellery ring necklace earring bracelet gold silver diamond',
    'gem sparkle shine charm',
    'jewelry shop',
  ],
  retail__shoes: ['Shoes', 'shoe sneaker boot footwear sandal heel', 'step stride sole kick', 'shoes shop'],
  retail__beauty_cosmetics: [
    'Beauty & cosmetics',
    'beauty cosmetic makeup skincare skin lipstick cream serum',
    'glow bloom blush glam',
    'beauty shop',
  ],
  retail__home_decor: [
    'Home decor',
    'decor home interior decoration candle cushion vase',
    'nest cozy haven hearth',
    'house shop',
  ],
  retail__furniture: [
    'Furniture',
    'furniture sofa chair table bed wardrobe cabinet',
    'oak craft frame seat',
    'furniture shop',
  ],
  retail__electronics: [
    'Electronics',
    'electronics gadget phone laptop headphone camera charger device',
    'volt spark circuit pixel',
    'store tech',
  ],
  retail__books: [
    'Books',
    'book bookstore novel author reading literature paperback',
    'page chapter ink shelf',
    'books shop',
  ],
  retail__toys: ['Toys', 'toy game puzzle doll kid lego plush', 'play fun joy tiny', 'toys shop'],
  retail__gifts: [
    'Gifts',
    'gift present hamper personalised personalized surprise',
    'wrap bow joy surprise',
    'gifts shop',
  ],
  retail__handmade_crafts: [
    'Handmade & crafts',
    'handmade craft artisan handcrafted pottery knit crochet',
    'craft maker loom kiln',
    'shop art',
  ],
  retail__sporting_goods: [
    'Sporting goods',
    'sport equipment gear bat ball racket cycling outdoor',
    'gear pro play field',
    'shop',
  ],
  retail__pet_supplies: [
    'Pet supplies',
    'pet supply food toy leash collar treat',
    'paw tail bark purr',
    'pet shop',
  ],
  retail__general_store: [
    'General store',
    'store shop everything variety marketplace online buy',
    'shop cart deal basket',
    'store shop',
  ],
  tech__saas_b2b: [
    'Business software (SaaS)',
    'saas software platform business dashboard team workflow automation',
    'flow stack hub sync',
    'app io software',
  ],
  tech__developer_tools: [
    'Developer tools',
    'developer code api debug database cli sdk git devops',
    'code stack byte forge',
    'dev io sh',
  ],
  tech__ai_ml: [
    'AI & machine learning',
    'ai artificial intelligence machine learning model neural llm',
    'mind neural logic sense',
    'ai io tech',
  ],
  tech__mobile_apps: ['Mobile apps', 'app mobile android ios smartphone', 'tap swipe pocket go', 'app'],
  tech__cybersecurity: [
    'Cybersecurity',
    'security cybersecurity threat vulnerability firewall encryption',
    'shield guard lock vault',
    'security tech',
  ],
  tech__data_analytics: [
    'Data & analytics',
    'data analytics dashboard report insight metric bi',
    'insight metric chart lens',
    'io tech',
  ],
  tech__cloud_hosting: [
    'Cloud & hosting',
    'cloud hosting server vps deploy infrastructure',
    'cloud host node edge',
    'cloud host',
  ],
  tech__web_design_dev: [
    'Web design & development',
    'website web design developer wordpress frontend agency',
    'pixel build craft site',
    'design dev studio',
  ],
  tech__it_services: [
    'IT services',
    'it support service network helpdesk outsourcing',
    'tech fix net support',
    'tech services',
  ],
  tech__hardware_iot: [
    'Hardware & IoT',
    'hardware iot sensor device robot electronics embedded',
    'bolt sensor wire chip',
    'tech io',
  ],
  tech__open_source: [
    'Open source',
    'open source github library project contributor community',
    'open forge hub kit',
    'dev io org',
  ],
  finance__banking_fintech: [
    'Banking & fintech',
    'bank banking fintech account wallet neobank',
    'coin vault ledger',
    'finance money',
  ],
  finance__investing: [
    'Investing',
    'invest investing stock fund portfolio trading market',
    'grow yield stock capital',
    'capital finance',
  ],
  finance__insurance: [
    'Insurance',
    'insurance insure policy cover claim premium',
    'cover shield safe guard',
    'insure',
  ],
  finance__accounting_tax: [
    'Accounting & tax',
    'accounting accountant tax bookkeeping audit invoice payroll',
    'ledger sum tally book',
    'tax accountant',
  ],
  finance__crypto_web3: [
    'Crypto & web3',
    'crypto cryptocurrency bitcoin blockchain web3 token nft defi',
    'chain block token coin',
    'xyz finance',
  ],
  finance__personal_finance: [
    'Personal finance',
    'budget saving money personal finance debt retire',
    'save coin wise plan',
    'money finance',
  ],
  finance__payments: [
    'Payments',
    'payment pay checkout gateway transfer remittance',
    'pay swift send flow',
    'money finance',
  ],
  finance__lending: [
    'Lending',
    'loan lending credit borrow mortgage microfinance',
    'lend credit fund',
    'loans credit',
  ],
  health__clinic_doctor: [
    'Clinic & doctor',
    'clinic doctor physician hospital medical patient appointment',
    'care cure heal well',
    'clinic health doctor',
  ],
  health__dental: [
    'Dental',
    'dental dentist tooth teeth orthodontist smile',
    'smile tooth bright',
    'dental dentist',
  ],
  health__mental_health_therapy: [
    'Mental health & therapy',
    'therapy therapist counselling counseling mental anxiety psychologist',
    'calm mind ease heal',
    'health care',
  ],
  health__fitness_gym: [
    'Fitness & gym',
    'gym fitness workout training trainer exercise muscle',
    'fit pulse lift strong',
    'fitness fit',
  ],
  health__yoga_meditation: [
    'Yoga & meditation',
    'yoga meditation mindfulness breath retreat',
    'zen calm flow breath',
    'yoga',
  ],
  health__nutrition_diet: [
    'Nutrition & diet',
    'nutrition diet dietitian nutritionist meal plan weight',
    'nourish fuel lean',
    'diet health',
  ],
  health__pharmacy: [
    'Pharmacy',
    'pharmacy chemist medicine drug prescription',
    'cure dose remedy',
    'pharmacy health',
  ],
  health__ayurveda_alternative: [
    'Ayurveda & alternative medicine',
    'ayurveda herbal homeopathy naturopathy acupuncture holistic',
    'herb root balance',
    'health',
  ],
  health__elder_care: [
    'Elder care',
    'elder elderly senior aged care nursing home',
    'care kind comfort',
    'care',
  ],
  health__veterinary: [
    'Veterinary',
    'vet veterinary veterinarian animal pet clinic',
    'paw care heal',
    'vet pet',
  ],
  education__school: [
    'School',
    'school student teacher class kindergarten primary secondary',
    'learn bright class',
    'school academy',
  ],
  education__coaching_tutoring: [
    'Coaching & tutoring',
    'tutor tutoring coaching lesson tuition homework',
    'tutor guide spark',
    'academy education',
  ],
  education__online_courses: [
    'Online courses',
    'course online learn lesson video certificate class',
    'learn skill path',
    'courses academy',
  ],
  education__test_prep: [
    'Test preparation',
    'exam test preparation prep entrance mock score',
    'ace prep score',
    'academy education',
  ],
  education__language_learning: [
    'Language learning',
    'language spanish english french learn speak fluent grammar',
    'speak lingo word talk',
    'academy school',
  ],
  education__kids_learning: [
    'Kids learning',
    'kid child learning preschool toddler early',
    'little bright tiny',
    'school fun',
  ],
  education__university: [
    'University',
    'university college campus degree faculty',
    'campus scholar quad',
    'university education',
  ],
  education__skills_training: [
    'Skills training',
    'training skill workshop bootcamp professional certification',
    'skill train build',
    'training academy',
  ],
  services__legal: [
    'Legal services',
    'law lawyer legal attorney advocate court contract',
    'law counsel justice',
    'legal lawyer',
  ],
  services__consulting: [
    'Consulting',
    'consulting consultant advisory strategy management',
    'advise insight strategy',
    'consulting',
  ],
  services__marketing_agency: [
    'Marketing agency',
    'marketing seo advertising social media agency brand campaign',
    'reach brand buzz growth',
    'agency marketing',
  ],
  services__design_studio: [
    'Design studio',
    'design designer graphic logo branding illustration',
    'studio pixel craft',
    'design studio',
  ],
  services__photography: [
    'Photography',
    'photography photographer photo portrait wedding shoot',
    'lens frame shot light',
    'photography photo',
  ],
  services__video_production: [
    'Video production',
    'video production film editing animation commercial',
    'reel frame cut take',
    'video studio',
  ],
  services__cleaning: [
    'Cleaning',
    'cleaning cleaner housekeeping maid laundry janitorial',
    'shine fresh sparkle',
    'cleaning',
  ],
  services__repair_maintenance: [
    'Repair & maintenance',
    'repair fix plumber electrician handyman maintenance',
    'fix fix tool handy',
    'services',
  ],
  services__logistics_courier: [
    'Logistics & courier',
    'courier logistics shipping delivery freight parcel',
    'ship route swift cargo',
    'delivery',
  ],
  services__recruitment_hr: [
    'Recruitment & HR',
    'recruitment recruiter hiring job hr talent staffing',
    'talent hire match',
    'careers jobs',
  ],
  services__event_planning: [
    'Event planning',
    'event planner planning party conference venue',
    'gather plan host',
    'events',
  ],
  services__wedding_services: [
    'Wedding services',
    'wedding bride groom bridal marriage planner',
    'vow bliss forever',
    'wedding',
  ],
  services__printing: [
    'Printing',
    'print printing printer poster card banner',
    'ink press sheet',
    'services',
  ],
  services__translation: [
    'Translation',
    'translation translator translate interpreter localization',
    'word bridge lingo',
    'services',
  ],
  real_estate__property_listings: [
    'Property listings',
    'property listing rent sale flat apartment house home',
    'nest key home door',
    'properties homes',
  ],
  real_estate__real_estate_agency: [
    'Real estate agency',
    'real estate realtor agent broker property',
    'key nest estate',
    'realty homes',
  ],
  real_estate__construction: [
    'Construction',
    'construction builder contractor build renovation',
    'build brick beam',
    'construction build',
  ],
  real_estate__interior_design: [
    'Interior design',
    'interior designer decor renovation space',
    'space nest form',
    'design',
  ],
  real_estate__architecture: [
    'Architecture',
    'architect architecture building design',
    'form arch line',
    'architect',
  ],
  real_estate__coworking_rentals: [
    'Coworking & rentals',
    'coworking office desk workspace rental',
    'desk hive space hub',
    'space',
  ],
  travel__travel_agency: [
    'Travel agency',
    'travel agency trip package holiday booking flight',
    'trip voyage journey',
    'travel holiday',
  ],
  travel__hotel_homestay: [
    'Hotel & homestay',
    'hotel homestay hostel resort stay guesthouse villa',
    'stay rest inn haven',
    'hotel',
  ],
  travel__tours_experiences: [
    'Tours & experiences',
    'tour guide experience trek adventure sightseeing',
    'roam trail wander',
    'tours',
  ],
  travel__transport_rental: [
    'Transport & rentals',
    'rental rent car bike taxi cab transfer',
    'ride drive go',
    'rentals',
  ],
  travel__travel_blog: [
    'Travel blog',
    'travel blog traveller traveler backpack wanderlust',
    'wander roam nomad',
    'travel blog',
  ],
  media__news: ['News', 'news journalism headline report breaking', 'daily wire herald', 'news press'],
  media__magazine: ['Magazine', 'magazine edition issue feature editorial', 'issue page edit', 'media'],
  media__blog_personal: ['Personal blog', 'blog blogger journal diary thought', 'note muse journal', 'blog'],
  media__podcast: ['Podcast', 'podcast episode listen audio show', 'cast echo mic', 'fm show'],
  media__video_channel: [
    'Video channel',
    'youtube channel video vlog creator stream',
    'reel play clip',
    'tv video',
  ],
  media__music: ['Music', 'music musician band song album artist dj', 'beat tune note rhythm', 'music band'],
  media__film: ['Film', 'film movie cinema filmmaker director', 'reel scene frame', 'film movie'],
  media__photography_art: [
    'Art & illustration',
    'art artist painting illustration gallery drawing',
    'canvas brush color',
    'art gallery',
  ],
  media__writing_publishing: [
    'Writing & publishing',
    'writer writing publish publishing author poetry',
    'ink quill page',
    'press',
  ],
  community__forum: [
    'Forum',
    'forum discussion thread board question answer',
    'talk thread hive',
    'community',
  ],
  community__club_association: [
    'Club & association',
    'club association society member meetup',
    'club circle guild',
    'club',
  ],
  community__religious_spiritual: [
    'Religious & spiritual',
    'church temple mosque faith spiritual prayer religious',
    'faith grace light',
    'church',
  ],
  community__alumni: [
    'Alumni network',
    'alumni graduate batch reunion network',
    'bond class circle',
    'community',
  ],
  community__local_community: [
    'Local community',
    'local neighbourhood neighborhood community resident town',
    'local town square',
    'community',
  ],
  community__fan_community: [
    'Fan community',
    'fan fandom fanclub supporter',
    'fan crew squad',
    'club community',
  ],
  nonprofit__charity: [
    'Charity',
    'charity donate donation fundraising help poor',
    'give hope heart',
    'charity org foundation',
  ],
  nonprofit__ngo_development: [
    'NGO & development',
    'ngo development empowerment rural welfare volunteer',
    'hope uplift rise',
    'ngo org',
  ],
  nonprofit__environment: [
    'Environment',
    'environment climate sustainability conservation tree plastic',
    'earth green leaf',
    'earth eco green',
  ],
  nonprofit__animal_welfare: [
    'Animal welfare',
    'animal rescue shelter adopt adoption stray welfare',
    'paw rescue haven',
    'org pet',
  ],
  nonprofit__education_charity: [
    'Education charity',
    'education charity scholarship literacy underprivileged',
    'learn hope bright',
    'org foundation',
  ],
  nonprofit__health_charity: [
    'Health charity',
    'health charity cancer awareness patient support',
    'hope care heal',
    'org foundation',
  ],
  lifestyle__parenting: [
    'Parenting',
    'parent parenting mom dad baby toddler family',
    'nest little bloom',
    'family',
  ],
  lifestyle__relationships_dating: [
    'Relationships & dating',
    'dating relationship love match single couple',
    'match spark heart',
    'love dating',
  ],
  lifestyle__home_garden: [
    'Home & garden',
    'garden gardening plant home yard',
    'bloom sprout root',
    'garden',
  ],
  lifestyle__diy: ['DIY', 'diy project craft maker tutorial', 'make build tinker', 'tips'],
  lifestyle__hobbies: ['Hobbies', 'hobby collect collector model craft', 'hobby kit club', 'club'],
  lifestyle__fashion_blog: [
    'Fashion blog',
    'fashion style blogger outfit trend',
    'style chic vogue',
    'fashion style',
  ],
  lifestyle__beauty_blog: [
    'Beauty blog',
    'beauty blogger makeup skincare review',
    'glow blush glam',
    'beauty',
  ],
  lifestyle__luxury: ['Luxury', 'luxury premium exclusive designer elite', 'luxe gold prime', 'luxury'],
  automotive__car_dealer: [
    'Car dealer',
    'car dealer used vehicle sale showroom',
    'drive wheel motor',
    'cars auto',
  ],
  automotive__auto_repair: [
    'Auto repair',
    'garage mechanic auto repair service tyre tire',
    'gear fix motor',
    'auto',
  ],
  automotive__ev_mobility: [
    'EV & mobility',
    'ev electric vehicle charging scooter mobility',
    'volt charge glide',
    'auto energy',
  ],
  automotive__bikes_motorcycles: [
    'Bikes & motorcycles',
    'bike bicycle motorcycle cycling scooter',
    'pedal ride spoke',
    'bike',
  ],
  entertainment__gaming: ['Gaming', 'game gaming gamer console pc play', 'quest level pixel', 'games gg'],
  entertainment__esports: [
    'Esports',
    'esports tournament team competitive gamer',
    'clutch squad arena',
    'gg games',
  ],
  entertainment__comedy: ['Comedy', 'comedy comedian standup funny joke', 'laugh grin pun', 'fun'],
  entertainment__events_nightlife: [
    'Events & nightlife',
    'nightlife club party concert dj event',
    'night beat vibe',
    'events live',
  ],
  entertainment__movies_tv: [
    'Movies & TV',
    'movie tv series show review stream',
    'reel binge screen',
    'tv movie',
  ],
  agriculture__farming: ['Farming', 'farm farmer farming crop harvest field', 'harvest field seed', 'farm'],
  agriculture__agritech: [
    'Agritech',
    'agritech agriculture technology precision drone soil',
    'sprout field yield',
    'farm tech',
  ],
  agriculture__dairy: ['Dairy', 'dairy milk cheese butter cow', 'milk cream churn', 'farm'],
  agriculture__plants_nursery: [
    'Plants & nursery',
    'plant nursery sapling succulent flower',
    'leaf sprout bloom',
    'garden',
  ],
  industry__manufacturing: [
    'Manufacturing',
    'manufacturing manufacturer factory production machine',
    'forge mill works',
    'industries',
  ],
  industry__energy_solar: [
    'Energy & solar',
    'solar energy power renewable panel wind',
    'sun volt power',
    'energy solar',
  ],
  industry__chemicals: ['Chemicals', 'chemical chemistry lab compound', 'lab element', 'industries'],
  industry__textiles: ['Textiles', 'textile fabric cotton yarn weaving', 'thread loom weave', 'industries'],
  industry__import_export: [
    'Import & export',
    'import export trade trading shipment',
    'trade port cargo',
    'trade',
  ],
  industry__wholesale: ['Wholesale', 'wholesale bulk distributor supplier', 'bulk supply', 'trade'],
  government_public__civic_services: [
    'Civic services',
    'government civic municipal public citizen service',
    'civic city public',
    'org',
  ],
  government_public__political_campaign: [
    'Political campaign',
    'campaign election candidate vote political party',
    'vote voice rise',
    'vote',
  ],
  personal__portfolio_cv: [
    'Portfolio & CV',
    'portfolio cv resume work freelance',
    'craft work folio',
    'me design',
  ],
  personal__personal_brand: [
    'Personal brand',
    'personal brand coach speaker creator influencer',
    'voice spark',
    'me name',
  ],
  personal__wedding_site: ['Wedding website', 'our wedding rsvp invitation couple', 'vow forever', 'wedding'],
  personal__family_site: ['Family website', 'family photo memory reunion', 'nest roots', 'family'],
  other__other: ['Other', 'other', '', ''],
};

export interface Industry {
  key: string;
  group: string;
  label: string;
  keywords: string[];
  wordHints: string[];
  tldHints: string[];
}

const split = (s: string) => s.split(' ').filter(Boolean);

export const TAXONOMY: readonly Industry[] = Object.entries(T).map(([key, [item, kw, words, tlds]]) => {
  const group = key.split('__')[0]!;
  return {
    key,
    group,
    label: group === 'other' ? 'Other' : `${GROUP_LABELS[group]} › ${item}`,
    keywords: split(kw),
    wordHints: [...new Set(split(words))],
    tldHints: split(tlds),
  };
});

/** `industry@1` options: key → label. */
export const INDUSTRY_OPTIONS: Record<string, string> = Object.fromEntries(
  TAXONOMY.map((i) => [i.key, i.label]),
);
