-- v1 schema (spec 012 tech §3, spec 011 tech §3, spec 005/007/010 tech §3). Approved 2026-10-03.
-- Rules: money in integer cents + ISO currency, times in timestamptz (FR-DATA-006); RLS on every table
-- (FR-DATA-004); no description column on anonymous search tables (FR-DATA-002).

-- ===== enums =====
create type public.check_status as enum
  ('available', 'likely_available', 'available_premium', 'taken', 'dropping_soon', 'unknown');
-- Internal section codes; the UI labels sections by price range only (spec 006 FR-PRC-003).
create type public.tier as enum ('free', 'budget', 'mid', 'premium');

-- ===== reference data (public read) =====
create table public.tlds (
  tld text primary key,                          -- 'com', 'co.in'
  type text not null check (type in ('gTLD', 'ccTLD', 'brand', 'sld')),
  rdap_base_url text,
  has_rdap boolean not null default false,
  dns_wildcard boolean not null default false,
  priced boolean not null default false,
  retired boolean not null default false,
  rdap_rps smallint,                             -- per-registry politeness override
  availability_notes text,
  updated_at timestamptz not null default now()
);

create table public.tld_policies (
  tld text primary key references public.tlds (tld),
  restriction text not null default 'none'
    check (restriction in ('none', 'local_presence', 'eligibility', 'blocked_for_public')),
  restriction_note text,
  min_years smallint not null default 1 check (min_years between 1 and 10),
  requires_https boolean not null default false,
  has_premium_names boolean not null default false,
  description text,
  reviewed_at date
);

create table public.tld_prices (
  tld text not null references public.tlds (tld),
  provider text not null,
  currency char(3) not null default 'USD',
  register_cents int check (register_cents >= 0),
  renew_cents int check (renew_cents >= 0),
  transfer_cents int check (transfer_cents >= 0),
  is_promo boolean not null default false,
  fetched_at timestamptz not null,
  primary key (tld, provider)
);

create table public.tld_price_history (
  tld text not null,
  provider text not null,
  register_cents int,
  renew_cents int,
  changed_at timestamptz not null,
  primary key (tld, provider, changed_at)
);

create table public.fx_rates (
  base char(3) not null,
  quote char(3) not null,
  rate numeric(18, 8) not null check (rate > 0),
  as_of date not null,
  primary key (base, quote, as_of)
);

create table public.free_providers (
  id text primary key,                           -- 'is-a-dev'
  name text not null,
  suffix text not null,
  kind text not null check (kind in ('subdomain_service', 'community_registry', 'platform_address')),
  eligibility jsonb not null,
  steps text[] not null,
  wait_time text,
  official_url text not null,
  check_method text not null check (check_method in ('github_tree', 'doh', 'none')),
  check_config jsonb,
  healthy boolean not null default true,
  health_note text,
  last_health_at timestamptz,
  reviewed_at date not null
);

-- ===== server-only reference data and caches =====
create table public.domain_checks (
  fqdn text primary key,
  tld text not null references public.tlds (tld),
  status public.check_status not null,
  method text not null check (method in ('dns', 'rdap', 'registrar', 'nrd')),
  premium_price_cents int,
  premium_currency char(3),
  premium_source text,
  drop_window_start date,
  drop_window_end date,
  checked_at timestamptz not null,
  expires_at timestamptz not null
);
create index domain_checks_expires on public.domain_checks (expires_at);
create index domain_checks_tld_status on public.domain_checks (tld, status);

create table public.free_provider_taken (
  provider_id text not null references public.free_providers (id) on delete cascade,
  label text not null,
  synced_at timestamptz not null,
  primary key (provider_id, label)
);

create table public.brand_labels (
  label text primary key,
  best_rank int not null,
  source text not null
);

create table public.keyword_trends (
  day date not null,
  token text not null,
  kind text not null,
  count int not null,
  primary key (day, kind, token)
);

create table public.word_cache (
  term text not null,
  relation text not null,
  words jsonb not null,
  fetched_at timestamptz not null,
  primary key (term, relation)
);

-- ===== searches (no description column by design, FR-DATA-002) =====
create table public.searches (
  id uuid primary key,                           -- uuidv7 generated by the app
  user_id uuid references auth.users (id) on delete set null,
  cache_key text not null,
  status text not null check (status in ('running', 'done', 'refused', 'needs_detail', 'error')),
  prefs jsonb not null,
  features jsonb,
  degraded boolean not null default false,
  jev_tokens int not null default 0,
  duration_ms int,
  stage_ms jsonb,
  pipeline_version text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
comment on table public.searches is 'No description column by design (spec 012 FR-DATA-002, constitution P5).';
create index searches_expires on public.searches (expires_at);

create table public.search_results (
  search_id uuid not null references public.searches (id) on delete cascade,
  fqdn text not null,
  section text not null check (section in ('free', 'budget', 'mid', 'premium', 'dropping', 'unpriced')),
  rank int not null,
  score real not null,
  status text not null,
  upfront_cents int,
  renew_cents int,
  price_source text,
  signals jsonb not null,
  reasons jsonb not null,
  strategy text not null,
  primary key (search_id, fqdn)
);

create table public.result_cache (
  cache_key text primary key,
  search_id uuid references public.searches (id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

-- ===== feedback (pseudonymous) =====
create table public.feedback (
  search_id uuid not null,
  fqdn text not null,
  visitor_hash text not null,                    -- daily-rotating HMAC, never an IP (FR-DATA-011)
  vote smallint not null check (vote in (-1, 1)),
  reason text check (reason in ('offensive', 'brand', 'other')),
  created_at timestamptz not null default now(),
  primary key (search_id, fqdn, visitor_hash)
);
create index feedback_created on public.feedback (created_at);

create table public.result_events (
  id bigint generated always as identity primary key,
  search_id uuid,
  fqdn text,
  action text not null,
  created_at timestamptz not null default now()
);
create index result_events_created on public.result_events (created_at);

create table public.feedback_monthly (
  month date not null,
  section text not null,
  strategy text not null,
  votes_up int not null default 0,
  votes_down int not null default 0,
  buy_clicks int not null default 0,
  copies int not null default 0,
  primary key (month, section, strategy)
);

-- ===== user data (spec 011 tech §3) =====
create table public.profiles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text check (char_length(display_name) <= 60),
  alerts_frequency text not null default 'daily' check (alerts_frequency in ('daily', 'weekly', 'off')),
  currency char(3) not null default 'USD',
  email_status text not null default 'ok' check (email_status in ('ok', 'bouncing', 'unsubscribed')),
  terms_version text not null,
  terms_accepted_at timestamptz not null,
  age_confirmed boolean not null check (age_confirmed),   -- 18+ (spec 013 FR-PRIV-008)
  created_at timestamptz not null default now()
);

create table public.saved_searches (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null check (char_length(title) <= 80),
  -- null for signed-out (anonymous) savers; RLS below blocks descriptions from anonymous sessions
  description text check (description is null or char_length(description) between 20 and 2000),
  preferences jsonb not null,
  search_id uuid,
  alerts_enabled boolean not null default true,
  last_checked_at timestamptz,
  created_at timestamptz not null default now()
);
create index saved_searches_user on public.saved_searches (user_id);

create table public.watchlist (
  user_id uuid not null references auth.users (id) on delete cascade,
  fqdn text not null,
  notify_on text[] not null default '{status_change}',
  last_status public.check_status,
  last_upfront_cents int,
  last_checked_at timestamptz,
  added_at timestamptz not null default now(),
  primary key (user_id, fqdn)
);

create table public.notifications (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  kind text not null check (kind in ('registered', 'available', 'dropping_soon', 'price_change')),
  fqdn text not null,
  payload jsonb,
  created_at timestamptz not null default now(),
  emailed_at timestamptz,
  read_at timestamptz
);
create index notifications_user_created on public.notifications (user_id, created_at desc);

-- Signed-out savers (spec 011 tech §5.6); removed 90 days after last use (spec 012 §5.2).
create table public.anon_visitors (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);
create index anon_visitors_last_seen on public.anon_visitors (last_seen_at);

-- ===== contact / grievance (spec 013) =====
create table public.contact_messages (
  id bigint generated always as identity primary key,
  email text not null,
  message text not null check (char_length(message) <= 4000),
  created_at timestamptz not null default now(),
  handled_at timestamptz
);

-- ===== operations =====
create table public.jev_usage (
  day date primary key,
  input_tokens bigint not null default 0,
  requests int not null default 0,
  searches int not null default 0,
  degraded_searches int not null default 0,
  eval_tokens bigint not null default 0
);

create table public.email_log (
  day date not null,
  provider text not null,
  sent int not null default 0,
  primary key (day, provider)
);

create table public.job_runs (
  id bigint generated always as identity primary key,
  job text not null,
  run_date date not null,
  status text not null check (status in ('running', 'success', 'failed', 'skipped')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  stats jsonb,
  error text
);
create index job_runs_job_started on public.job_runs (job, started_at desc);

create table public.quality_reports (
  id bigint generated always as identity primary key,
  kind text not null,
  period text not null,
  metrics jsonb not null,
  created_at timestamptz not null default now()
);

create table public.search_metrics_daily (
  day date primary key,
  searches int, cache_hits int, p50_ms int, p95_ms int,
  p50_stage_ms jsonb, p95_stage_ms jsonb, avg_tokens int,
  degraded int, refused int, needs_detail int,
  actions int, thumbs_up int, thumbs_down int
);

-- ===== limits (spec 011: 20 saved searches, 100 watched names per user) =====
create function public.enforce_user_limit() returns trigger
language plpgsql
set search_path = ''
as $$
declare
  max_rows int := tg_argv[0]::int;
  n int;
begin
  perform pg_advisory_xact_lock(hashtext(tg_table_name || new.user_id::text));
  execute format('select count(*) from public.%I where user_id = $1', tg_table_name) into n using new.user_id;
  if n >= max_rows then
    raise exception 'limit_reached: at most % rows in %', max_rows, tg_table_name using errcode = 'P0001';
  end if;
  return new;
end;
$$;

create trigger saved_searches_limit before insert on public.saved_searches
  for each row execute function public.enforce_user_limit('20');
create trigger watchlist_limit before insert on public.watchlist
  for each row execute function public.enforce_user_limit('100');

-- ===== row level security: on for every table; no policy = no access for anon/authenticated =====
do $$
declare t record;
begin
  for t in select tablename from pg_tables where schemaname = 'public' loop
    execute format('alter table public.%I enable row level security', t.tablename);
  end loop;
end;
$$;

-- Public reference data (FR-DATA-005)
create policy public_read on public.tlds for select to anon, authenticated using (true);
create policy public_read on public.tld_policies for select to anon, authenticated using (true);
create policy public_read on public.tld_prices for select to anon, authenticated using (true);
create policy public_read on public.tld_price_history for select to anon, authenticated using (true);
create policy public_read on public.fx_rates for select to anon, authenticated using (true);
create policy public_read on public.free_providers for select to anon, authenticated using (true);

-- Own rows only (FR-DATA-004). `is_anonymous` comes from the Supabase JWT.
create policy own_select on public.profiles for select to authenticated using (user_id = (select auth.uid()));
create policy own_insert on public.profiles for insert to authenticated
  with check (user_id = (select auth.uid())
              and coalesce(((select auth.jwt()) ->> 'is_anonymous')::boolean, false) = false);
create policy own_update on public.profiles for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

create policy own_select on public.saved_searches for select to authenticated using (user_id = (select auth.uid()));
create policy own_insert on public.saved_searches for insert to authenticated
  with check (user_id = (select auth.uid())
              and (description is null
                   or coalesce(((select auth.jwt()) ->> 'is_anonymous')::boolean, false) = false));
create policy own_update on public.saved_searches for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid())
              and (description is null
                   or coalesce(((select auth.jwt()) ->> 'is_anonymous')::boolean, false) = false));
create policy own_delete on public.saved_searches for delete to authenticated using (user_id = (select auth.uid()));

create policy own_select on public.watchlist for select to authenticated using (user_id = (select auth.uid()));
create policy own_insert on public.watchlist for insert to authenticated with check (user_id = (select auth.uid()));
create policy own_update on public.watchlist for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy own_delete on public.watchlist for delete to authenticated using (user_id = (select auth.uid()));

create policy own_select on public.notifications for select to authenticated using (user_id = (select auth.uid()));
create policy own_update on public.notifications for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));

create policy own_select on public.anon_visitors for select to authenticated using (user_id = (select auth.uid()));

-- ===== RPCs (service role only) =====
create function public.jev_usage_add(p_day date, p_tokens bigint, p_requests int, p_degraded boolean)
returns void
language sql
security definer
set search_path = ''
as $$
  insert into public.jev_usage as u (day, input_tokens, requests, searches, degraded_searches)
  values (p_day, p_tokens, p_requests, 1, case when p_degraded then 1 else 0 end)
  on conflict (day) do update set
    input_tokens = u.input_tokens + excluded.input_tokens,
    requests = u.requests + excluded.requests,
    searches = u.searches + 1,
    degraded_searches = u.degraded_searches + excluded.degraded_searches;
$$;

create function public.month_jev_tokens(p_month date) returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(sum(input_tokens), 0)::bigint from public.jev_usage
  where day >= date_trunc('month', p_month)::date
    and day < (date_trunc('month', p_month) + interval '1 month')::date;
$$;

revoke execute on function public.jev_usage_add(date, bigint, int, boolean) from public, anon, authenticated;
revoke execute on function public.month_jev_tokens(date) from public, anon, authenticated;
grant execute on function public.jev_usage_add(date, bigint, int, boolean) to service_role;
grant execute on function public.month_jev_tokens(date) to service_role;
revoke execute on function public.enforce_user_limit() from public, anon, authenticated;
